# Common configuration.
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - vendor/assets/bower_components/**/*
    - Rakefile
    - Guardfile
    - bin/*
    - db/**/*
    - config/**/*
    - script/**/*
    - Rakefile
    - tmp/**/*
    - vendor/**/*
    - spec/support/**/*
    - spec/spec_helper.rb

LineLength:
  Enabled: true
  Max: 80

Documentation:
  Enabled: false

AlignHash:
  Enabled: false

# Buggy cop:
EndOfLine:
  Enabled: false

AsciiComments:
  Enabled: false

# Not working for breaks_paid? method
TrivialAccessors:
  Enabled: false

# Disabled since renaming has methods makes no sense
PredicateName:
  Enabled: false

IndentationConsistency:
  Enabled: false

ConditionPosition:
  Enabled: false

# We want to use the compact style of module definitions
ClassAndModuleChildren:
  Enabled: false

# Buggy cop:
BlockAlignment:
  Enabled: false

MethodLength:
  Enabled: true

AbcSize:
  Enabled: false

VariableNumber:
  EnforcedStyle: snake_case
  SupportedStyles:
  - snake_case
  - normalcase
  - non_integer

BlockLength:
  CountComments: false
  Max: 25
  Exclude:
  - 'Rakefile'
  - 'apps/api/application.rb'
  - '**/*.rake'
  - 'spec/**/*.rb'
  - 'test/**/*.rb'
